#!/usr/bin/env python3
"""HWDT — Jira provisioning (idempotent).

Creates from jira/configuration/hwdt-project.json:
  * custom issue types (Test Case, Change Request, Incident, Infrastructure Task)
  * custom fields (Module, Environment, Release Version, Priority Level, Test Result, Department, Employee ID)
  * project HWDT (Scrum software template), components, versions
  * the 8 epics EPIC-001..EPIC-008 (label = epic ref, idempotent via JQL)
  * renders OSWorkflow XML for both workflows with real status IDs (for Admin > Workflows > Import from XML)

Usage:
  python3 provision_jira.py                  # full provisioning against $JIRA_BASE_URL
  python3 provision_jira.py --render-only    # only (re)render workflow XML templates (offline)
"""
from __future__ import annotations

import sys
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
from hwdt_common import ROOT, ApiError, RestClient, load_json, log, require_env, wait_until_running, warn  # noqa: E402

import os  # noqa: E402

CONFIG = "jira/configuration/hwdt-project.json"


# ----------------------------------------------------------------------------- workflow XML
def _post_functions(event_id: int = 13, extra: str = "") -> str:
    fns = [
        extra,
        '<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.UpdateIssueStatusFunction</arg></function>',
        '<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.misc.CreateCommentFunction</arg></function>',
        '<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.GenerateChangeHistoryFunction</arg></function>',
        '<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.IssueReindexFunction</arg></function>',
        f'<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.event.FireIssueEventFunction</arg><arg name="eventTypeId">{event_id}</arg></function>',
    ]
    return "".join(f for f in fns if f)


def render_workflow_xml(wf: dict, status_ids: dict[str, str] | None = None) -> str:
    """Render an OSWorkflow 2.8 descriptor. Without status_ids, placeholders {{STATUS_ID:NAME}} are used."""
    statuses = [s["name"] for s in wf["statuses"]]
    step_id = {name: idx + 1 for idx, name in enumerate(statuses)}
    sid = lambda n: (status_ids or {}).get(n.upper(), f"{{{{STATUS_ID:{n}}}}}")  # noqa: E731
    action_id = 11
    actions_by_step: dict[str, list[str]] = {n: [] for n in statuses}
    for t in wf["transitions"]:
        extra = ""
        if t.get("resolution"):
            extra = ('<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.UpdateIssueFieldFunction</arg>'
                     '<arg name="field.value">10000</arg><arg name="field.name">resolution</arg></function>')
        if t.get("clearResolution"):
            extra = ('<function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.UpdateIssueFieldFunction</arg>'
                     '<arg name="field.value"></arg><arg name="field.name">resolution</arg></function>')
        actions_by_step[t["from"]].append(
            f'<action id="{action_id}" name="{escape(t["name"])}">'
            '<meta name="jira.description"></meta><meta name="jira.fieldscreen.id"></meta>'
            f'<results><unconditional-result old-status="null" status="null" step="{step_id[t["to"]]}">'
            f"<post-functions>{_post_functions(extra=extra)}</post-functions>"
            "</unconditional-result></results></action>"
        )
        action_id += 10

    steps = []
    for name in statuses:
        acts = actions_by_step[name]
        steps.append(
            f'  <step id="{step_id[name]}" name="{escape(name)}">\n'
            f'    <meta name="jira.status.id">{sid(name)}</meta>\n'
            + (f"    <actions>{''.join(acts)}</actions>\n" if acts else "")
            + "  </step>"
        )
    first = statuses[0]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE workflow PUBLIC "-//OpenSymphony Group//DTD OSWorkflow 2.8//EN" "http://www.opensymphony.com/osworkflow/workflow_2_8.dtd">
<!-- {escape(wf['name'])} — generated by scripts/provision/provision_jira.py from {CONFIG}. Do not edit by hand. -->
<workflow>
  <meta name="jira.description">{escape(wf['description'])}</meta>
  <meta name="jira.update.author.key">admin</meta>
  <initial-actions>
    <action id="1" name="Create">
      <validators>
        <validator name="" type="class"><arg name="permission">Create Issue</arg><arg name="class.name">com.atlassian.jira.workflow.validator.PermissionValidator</arg></validator>
      </validators>
      <results>
        <unconditional-result old-status="null" status="open" step="{step_id[first]}">
          <post-functions>
            <function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.IssueCreateFunction</arg></function>
            <function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.issue.IssueReindexFunction</arg></function>
            <function type="class"><arg name="class.name">com.atlassian.jira.workflow.function.event.FireIssueEventFunction</arg><arg name="eventTypeId">1</arg></function>
          </post-functions>
        </unconditional-result>
      </results>
    </action>
  </initial-actions>
  <steps>
{chr(10).join(steps)}
  </steps>
</workflow>
"""


def workflow_filename(wf: dict) -> str:
    return wf["name"].lower().replace(" ", "-") + ".xml"


def render_all(cfg: dict, out_dir: Path, status_ids: dict[str, str] | None = None) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for wf in cfg["workflows"]:
        p = out_dir / workflow_filename(wf)
        p.write_text(render_workflow_xml(wf, status_ids), encoding="utf-8")
        written.append(p)
        log(f"rendered {p}")
    return written


# ----------------------------------------------------------------------------- provisioning
def ensure_issue_types(jira: RestClient, cfg: dict) -> None:
    existing = {t["name"].lower(): t for t in jira.get("/rest/api/2/issuetype")}
    for it in cfg["issueTypes"]:
        if it["name"].lower() in existing:
            log(f"issue type '{it['name']}' exists (id={existing[it['name'].lower()]['id']})")
            continue
        created = jira.post("/rest/api/2/issuetype", {"name": it["name"], "description": it["description"], "type": it["type"]})
        log(f"created issue type '{it['name']}' (id={created['id']})")


def ensure_custom_fields(jira: RestClient, cfg: dict) -> dict[str, str]:
    fields = jira.get("/rest/api/2/field")
    by_name = {f["name"].lower(): f for f in fields if f.get("custom")}
    ids: dict[str, str] = {}
    for cf in cfg["customFields"]:
        if cf["name"].lower() in by_name:
            ids[cf["name"]] = by_name[cf["name"].lower()]["id"]
            log(f"custom field '{cf['name']}' exists ({ids[cf['name']]})")
        else:
            created = jira.post("/rest/api/2/field", {
                "name": cf["name"], "description": cf["description"],
                "type": cf["type"], "searcherKey": cf["searcherKey"],
            })
            ids[cf["name"]] = created["id"]
            log(f"created custom field '{cf['name']}' ({created['id']})")
        if cf["options"]:
            _ensure_options(jira, ids[cf["name"]], cf)
    return ids


def _ensure_options(jira: RestClient, field_id: str, cf: dict) -> None:
    """Jira DC has no official REST endpoint for option management; try the known endpoints, else report."""
    numeric = field_id.replace("customfield_", "")
    try:
        existing = jira.get(f"/rest/api/2/customFields/{numeric}/options")
        values = {o.get("value") for o in existing.get("values", [])}
        missing = [o for o in cf["options"] if o not in values]
    except ApiError:
        missing = cf["options"]
    if not missing:
        log(f"  options for '{cf['name']}' present")
        return
    try:
        jira.post(f"/rest/api/2/field/{field_id}/context/default/option", {"options": [{"value": o} for o in missing]})
        log(f"  added {len(missing)} option(s) to '{cf['name']}'")
    except ApiError:
        warn(f"  add options to '{cf['name']}' via Admin > Issues > Custom fields > Configure: {', '.join(missing)}")


def ensure_project(jira: RestClient, cfg: dict, lead: str) -> dict:
    p = cfg["project"]
    try:
        project = jira.get(f"/rest/api/2/project/{p['key']}")
        log(f"project {p['key']} exists (id={project['id']})")
    except ApiError as e:
        if e.status != 404:
            raise
        project = jira.post("/rest/api/2/project", {
            "key": p["key"], "name": p["name"], "description": p["description"],
            "projectTypeKey": p["projectTypeKey"], "projectTemplateKey": p["projectTemplateKey"],
            "lead": lead, "assigneeType": p["assigneeType"],
        })
        log(f"created project {p['key']} (id={project['id']})")
    comps = {c["name"] for c in jira.get(f"/rest/api/2/project/{p['key']}/components")}
    for c in p["components"]:
        if c["name"] not in comps:
            jira.post("/rest/api/2/component", {"project": p["key"], **c})
            log(f"  component '{c['name']}' created")
    versions = {v["name"] for v in jira.get(f"/rest/api/2/project/{p['key']}/versions")}
    for v in cfg.get("versions", []):
        if v["name"] not in versions:
            jira.post("/rest/api/2/version", {"project": p["key"], **v})
            log(f"  version '{v['name']}' created")
    return project


def ensure_epics(jira: RestClient, cfg: dict, field_ids: dict[str, str]) -> None:
    key = cfg["project"]["key"]
    all_fields = jira.get("/rest/api/2/field")
    epic_name_id = next((f["id"] for f in all_fields if f["name"] == "Epic Name"), None)
    for epic in cfg["epics"]:
        label = epic["ref"].lower()
        found = jira.get("/rest/api/2/search", jql=f'project = {key} AND issuetype = Epic AND labels = "{label}"', maxResults=1)
        if found.get("total", 0) > 0:
            log(f"epic {epic['ref']} exists ({found['issues'][0]['key']})")
            continue
        fields = {
            "project": {"key": key},
            "issuetype": {"name": "Epic"},
            "summary": f"{epic['ref']} {epic['name']}",
            "description": epic["description"],
            "labels": [label, "hwdt-epic"],
        }
        if epic_name_id:
            fields[epic_name_id] = epic["name"]
        if "Module" in field_ids:
            fields[field_ids["Module"]] = {"value": epic["module"]}
        try:
            created = jira.post("/rest/api/2/issue", {"fields": fields})
        except ApiError:
            fields.pop(field_ids.get("Module", "_"), None)   # field not on screen yet -> retry without it
            created = jira.post("/rest/api/2/issue", {"fields": fields})
        log(f"created epic {epic['ref']} -> {created['key']}")


def status_id_map(jira: RestClient) -> dict[str, str]:
    return {s["name"].upper(): s["id"] for s in jira.get("/rest/api/2/status")}


def main() -> None:
    cfg = load_json(CONFIG)
    templates = ROOT / "jira/configuration/workflows"
    if "--render-only" in sys.argv:
        render_all(cfg, templates)
        return

    base = os.environ.get("JIRA_BASE_URL", "http://jira:8080")
    user = os.environ.get("JIRA_ADMIN_USER", "admin")
    wait_until_running(base, "Jira")
    jira = RestClient(base, user, require_env("JIRA_ADMIN_PASSWORD"))

    ensure_issue_types(jira, cfg)
    field_ids = ensure_custom_fields(jira, cfg)
    ensure_project(jira, cfg, user)
    ensure_epics(jira, cfg, field_ids)

    ids = status_id_map(jira)
    needed = sorted({s["name"] for wf in cfg["workflows"] for s in wf["statuses"]})
    missing = [s for s in needed if s.upper() not in ids]
    out = Path(os.environ.get("HWDT_OUTPUT_DIR", "/tmp/hwdt-workflows"))
    if missing:
        warn("create these statuses in Admin > Issues > Statuses, then re-run: " + ", ".join(missing))
    render_all(cfg, out, ids)
    log(f"Import the XML in {out} via Admin > Issues > Workflows > Import from XML, "
        f"then associate '{cfg['workflowScheme']['name']}' with project {cfg['project']['key']}.")
    log("Jira provisioning finished")


if __name__ == "__main__":
    main()
